### ISSUE TITLE
Scent entities interfere with Thaumcraft

### ISSUE THREAD

**Issue by zauberparacelsus** [Corosauce/ZombieAwareness#1]
The entities spawned that allow zombies to track you are interfering with the use of the thaumometer in thaumcraft.  Namely, it will try to scan the scent entity instead of the item/block/mob that you are trying to look at.

Simply disabling scent tracking in the configuration doesn't help either, as the scent entities are still spawned even when they are not being used.

**Comment by Corosauce** [comment]
+1 reason to reconsider turning those entities into pure data I guess, I was originally going to do this but changing some 'can collide' flags and their size to 0,0 solved all problems I encoutered (except this one apparently), would be nice if thaumcraft could ignore entities that have a size of 0 and no collision, or have some sort of filter system. It probably doesn't though.

To remove scents still spawned, do "/coroutil kill scent", id suggest doing "/coroutil list scent" to make sure only my scents are listed so you dont accidentally kill off any other entities that might have scent in their name
