### ISSUE TITLE
Server crashes after joining with this mod

### ISSUE THREAD

**Issue by ZoyFetii** [Corosauce/ZombieAwareness#100]
**Hello I have a serious problem. I'll explain it to you below. Last Sunday I bought this server to play with 1 friend, and we were able to play perfectly. The fact is that I have not touched any file or anything on the server and related, and today when we go to play we find that the server turns on, but when we go to enter it clicks us floating in the apparent void. After a few seconds it kicks us out of the server and says timeout and moments later the server shuts down. Do you have any idea what it could be? Shall I pass you the Crash Report? I would appreciate a helpful answer. Thank you

PS: I've found that releasing the mod: Zombie Awareness fixes this problem, but for this mod pack, I need to have it on the server.**

**Comment by TelepathicGrunt** [comment]
Can you try this Zombie Awareness Freeze Fix mod and see if it helps resolve the freezing/deadlock that you are having? It might be that the item frames on world loading is affected as well. The fix in this mod is for world generation but may work to fix your specific issue as well. https://www.curseforge.com/minecraft/mc-mods/zombie-awareness-freeze-fix

**Comment by ZoyFetii** [comment]
Lo probaré, si funciona os lo haré saber. Muchas gracias de antemano.

**Comment by Corosauce** [comment]
Until I backport a proper fix I'll recommend that freeze-fix mod for now 👍
