### ISSUE TITLE
crashes on 1.18.2

### ISSUE THREAD

**Issue by Aceplante** [Corosauce/ZombieAwareness#101]
title

**Comment by CoDroStyle** [comment]
Also have this issue. 

Note: i have been adding each mod 1 by 1 to locate the dirty mod. Looks like it was this one. This mod set worked with the current list until i added zombieawareness.

Uploaded crash log. 

forge-1.18.2-40.1.85
preview_OptiFine_1.18.2_HD_U_H9_pre2

[crash-2023-03-31_20.32.13-fml.txt](https://github.com/Corosauce/ZombieAwareness/files/11120431/crash-2023-03-31_20.32.13-fml.txt)

Mods:
PresenceFootsteps-1.5.1
player-animation-lib-forge-1.0.2+1.18
player-animation-lib-forge-1.0.2+1.18
infernalmobs-1.18.6
farsightedmobs-forge-1.1-1.18
Enhanced_Celestials-forge-1.18.2-2.0.7
DynamicTrees-1.18.2-0.11.0-Beta8
DynamicSurroundings-5.0.0.4
cloth-config-6.4.90-forge
bettercombat-forge-1.6.2+1.18.2

**Comment by CoDroStyle** [comment]
> title

Make sure you have the foundation mod [coroutil.1.18.2-1.2.45] installed. 

I was crashing until i investigated and found i had missed it.

**Comment by festro** [comment]
I'm getting a crash too looks like an I\O error, here's the log
[crash-2023-05-28_09.00.23-client.txt](https://github.com/Corosauce/ZombieAwareness/files/11585045/crash-2023-05-28_09.00.23-client.txt)

**Comment by Aceplante** [comment]
I have coroutil tho
