### ISSUE TITLE
1.16.5 is crashing

### ISSUE THREAD

**Issue by ProWolfBest** [Corosauce/ZombieAwareness#106]
When i open minecraft with this mod on 1.16.5 i get an error message.
The error message:
Zombie Awearness has class loading errors
java.lang.NoClassDEfFoundError: com/corosus/modconfig/IConfigCategory

I hope i can get help with this issue as i really want to play with this mod.

**Comment by Danyko03** [comment]
happens the same with me, have you find any solution? I saw that happens some times when you run old mods in newer versions, so I think the mod is bad ported from 1.12 or something to 1.16.5

**Comment by Corosauce** [comment]
Install coroutil.
