### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mxnmnm** [Corosauce/ZombieAwareness#115]
Forge 1.20.1
https://gist.github.com/mxnmnm/fc4b5b0f92aa8f28b12006ab072eaf31

**Comment by Corosauce** [comment]
Fixed https://github.com/Corosauce/ZombieAwareness/commit/2ee529fa4d2f5287e4b5ec8dd4ae94f26f630a28

zombieawareness-1.20.1-1.13.1 build on the way.
