### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads (Crash) 1.20.1 

### ISSUE THREAD

**Issue by Silverbolt666** [Corosauce/ZombieAwareness#116]
Hi, on a personal modpack encountered an fatal crash.

The problem is occurring in the ZombieAwareness mod, particularly in the ZAUtil.giveRandomSpeedBoost method, where there is an attempt to access LegacyRandomSource from multiple threads simultaneously, leading to the IllegalStateException (According to ChatGPT)

Running on:
Minecraft: 1.20.1
Forge Loader: 47.2.0
Mod Version: 1.20.1-1.130.0

If more information is needed feel free to ask. I'll disable the mod for now.

[crash-2024-01-18_16.38.31-server.txt](https://github.com/Corosauce/ZombieAwareness/files/13979466/crash-2024-01-18_16.38.31-server.txt)

[latest.log](https://github.com/Corosauce/ZombieAwareness/files/13979473/latest.log)

**Comment by mxnmnm** [comment]
looks like the same issue I had

**Comment by Corosauce** [comment]
Fixed https://github.com/Corosauce/ZombieAwareness/commit/2ee529fa4d2f5287e4b5ec8dd4ae94f26f630a28

zombieawareness-1.20.1-1.13.1 build on the way.
