### ISSUE TITLE
Server crash on 1.11.1

### ISSUE THREAD

**Issue by tgstyle** [Corosauce/ZombieAwareness#12]
Didn't see what actually caused it. Here is the log.

https://gist.github.com/tgstyle/9e6e3986b72219b12f417775553bc9c6

Minecraft 1.10.2
Forge 2185

**Comment by Corosauce** [comment]
I should be able to fix, in the meantime, go into ZombieAwareness/General.cfg and set zombieRandSpeedBoost to 0 to disable what is causing the crash
