### ISSUE TITLE
Crash on worldload

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [Corosauce/ZombieAwareness#13]
Hi,

I'm getting the following crash when I start up my world, I'm currently in the nether.
The pack I'm playing is forever stranded on minecraft 1.10.2 (with foamfix installed).

Pastebin: http://pastebin.com/aJKDDXjb

**Comment by Corosauce** [comment]
I think I see the problem, pushing new build out.

**Comment by Corosauce** [comment]
Botched the first fix, pushing another out.
