### ISSUE TITLE
Server crash with java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Krysinski** [Corosauce/ZombieAwareness#14]
After upgrade Gregtech mod from  5.09.27 to  5.09.28 server has crash with `java.lang.OutOfMemoryError: Java heap space` when player try to connect (from 3500M with 0 players up to 6000M with one player)
[crash-2017-03-06_11.18.34-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/820543/crash-2017-03-06_11.18.34-server.txt)
With Gregtech 5.0.27 about 3500M of memory in use all time with same mods and no issues.

Issue was fixed in https://github.com/Blood-Asp/GT5-Unofficial/issues/931

**Comment by Corosauce** [comment]
in config/CoroUtil.cfg set chunkCacheOverworldOnly to true to prevent this from happening.
