### ISSUE TITLE
worldeventlistener nullpointer

### ISSUE THREAD

**Issue by Zottel** [Corosauce/ZombieAwareness#16]
1.10.2-1.11.5

java.lang.NullPointerException: Ticking player
	at ZombieAwareness.WorldEventListener.func_184375_a(WorldEventListener.java:49)
	at net.minecraft.world.World.func_184148_a(World.java:1061)

Full trace in:
https://gist.github.com/Zottel/143ce792eb4e0877fb85412de156a147

Happened after some time in my desert world...
We suspected the new desert husks to cause problems - maybe related?

**Comment by Corosauce** [comment]
Edit: Update to 1.11.6, see if it still happens, I changed some code that might have fixed that crash.
