### ISSUE TITLE
Mod does not use Husks and Strays

### ISSUE THREAD

**Issue by Generalcamo** [Corosauce/ZombieAwareness#17]
In 1.10+, Husks should replace Zombies in Desert Environments and Strays should replace Skeletons in Snow environments. 

This does not happen with Zombie Awareness.

**Comment by Corosauce** [comment]
How have I not seen a stray before, even regularly spawned before... I see strays in the code though, I should adjust my mob duplication and fresh spawning code to account for this yeah.

**Comment by Corosauce** [comment]
Forgot to close this, a new generic system was put in place that should have those covered now, and if not, you can config it to be used for them. Feel free to open a new issue for mobs if you run into problems.
