### ISSUE TITLE
[Suggestion]  Pillar Building and Block Breaking

### ISSUE THREAD

**Issue by Boolyman** [Corosauce/ZombieAwareness#18]
With Funwayguy kind of disssapearing from the modded seen due to RL school obligations, some of the issues with Epic Siege Mobs and BQM are not being addressed.  I have had to drop Epic Siege Mobs from my upcoming packs, and I dont doubt others have as well.  If there was any way that you could add a few of the key features to Zombie Awareness, that would allow your mod to kind of "take over" the Mob AI scene.   The biggest differences between ZA and ESM is that ESM gave mobs the AI to dig through blocks and pillar up to their target.  If you could add these features into ZA, your mod that would really help us out.

**Comment by Corosauce** [comment]
Good to know opportunity is increasing, I've actually got both digging and pillaring up planned/done for a different mod, "Hostile Worlds - Invasions", and sorda part of another side mod called "Hostile Worlds - Monsters". I've got a lot of experience with digging based mobs and have playtested my more recent versions of it to death, pillaring still needs to be added though, gotta keep those skybase builders on their toes! I'd love to have everything rolling in the next couple months, but I can get easily distracted. Heres a text I keep handy describing my Invasion mod plans (like 90% done at this point) http://coros.us/notes/hw_invasions.txt

**Comment by reddvilzz** [comment]
If I would suggest adding the delay feature or maybe any other feature you think you like from ESM into your mod that will makes it better. Just a suggestions.

**Comment by Miaourt** [comment]
<3

**Comment by Corosauce** [comment]
If by delay you mean not having the mod do its thing until a certain starting day, thats already in :D, a setting to do nothing until x amount of days have passed, and also a config to make an invasion happen every x days after that first delay has passed.

**Comment by Corosauce** [comment]
I was also working on a system to let you skip an invasion up to 3 times in a row, at a cost of making the next one harder. I made that feature after seeing other players and myself just sometimes not wanting to deal with an invasion because they are waist deep in whatever tech factory setup they were working on.

**Comment by reddvilzz** [comment]
Great! Even better delaying features. Can't wait to use it.

Will it exclusively for 1.10 +? Or 1.7.10 will have some love as well?

**Comment by Corosauce** [comment]
The remake is going to be for 1.10.2 and up, if you are feeling brave you can try the 1.7.10 build but it has a simpler 'digging zombies for invasions' focus and is 14 months old, and I don't support it at all https://minecraft.curseforge.com/projects/hostile-worlds-invasions

**Comment by reddvilzz** [comment]
I already used your Hostile World actually, but I'll use yours for 1.10. Thank you.

**Comment by VirtualGaming1** [comment]
@Corosauce your link in the last comment dose not work anymore since Twitch updated the website.

**Comment by Corosauce** [comment]
Fixed link
