### ISSUE TITLE
Crash on newest 1.10.2 version (1.11.7)

### ISSUE THREAD

**Issue by Dune-Jumper** [Corosauce/ZombieAwareness#19]
The game crashes randomly crashes while using the latest version. I went through and removed a bunch of mods until I figured out that Zombie Awareness was causing the crash. No more crashes after going back to 1.11.6. [Crash report](https://pastebin.com/WguAfqUG)

**Comment by Corosauce** [comment]
You didn't update CoroUtil, read the changelogs

**Comment by Dune-Jumper** [comment]
Huh, I downloaded it. I guess I forgot to replace the old one. Thanks for helping.
