### ISSUE TITLE
Disabling scent tracking does not stop the spawning of scent entities

### ISSUE THREAD

**Issue by NEXUS2345** [Corosauce/ZombieAwareness#2]
Disabling the spawning of blood/scent sense sources in the Features.cfg file did not stop the spawning of entityScent. This is causing issues with our server's entity limiter as we limit the number of spawned mobs to prevent TPS lag.

**Comment by Corosauce** [comment]
Looks like block mining was overlooked for the sound config that disables them, fixed: https://github.com/Corosauce/ZombieAwareness/commit/8e10a75d051ab0338c795ffcff5cae2a24f62c99

Disable wandering hordes too, they also spawn sense entities, infact I'm defaulting it to false now to reduce cpu load and give better chance for mobs to despawn.

Will push build with fix once I test out some new features more.
