### ISSUE TITLE
Blood Splatter "broken" on newer version of forge.

### ISSUE THREAD

**Issue by Krhymez** [Corosauce/ZombieAwareness#24]
In my pack i am using Binnies which for some reason likes to use Forge versions past recommend,  With that being said, forge versions 14.23.0.2536  through the most recent 2542  breaks the blood splatter of the mod.

**Comment by Corosauce** [comment]
I tried current latest 2581 and also 2536 and it works fine.

[http://share.coros.us/files/2017-12-21_21.31.39.png](http://share.coros.us/files/2017-12-21_21.31.39.png)
