### ISSUE TITLE
[1.12] Sounds from wrong mobs

### ISSUE THREAD

**Issue by Jomik** [Corosauce/ZombieAwareness#25]
The "alert" sounds come from other mobs that shouldn't have your AI.
I've set it so that the only `tickable_entities` is `Zombie and ZombieVillager`. But still I have the sounds coming from creepers, spiders and skeletons. 👎 
It sort of breaks the immersion, so I'd love a fix for this 👎

**Comment by Corosauce** [comment]
Can't reproduce, config is working perfect for me, tested with creeper targetting me, only made sound when I had "Creeper=true". Make sure to close the game when making changes in that config file.
