### ISSUE TITLE
Add license file?

### ISSUE THREAD

**Issue by alexbobp** [Corosauce/ZombieAwareness#26]
Hi, I'm putting together an all-open-source modpack to showcase the modding community's best work.  This is an awesome mod for making the game challenging in a smart way that isn't just making numbers bigger.  I'm not sure what your intent is with respect to licensing, but I thought I'd ask since it's on github.  I would really love to include this in my pack if you're willing to choose an open source license.  If would be a big boon to the modding community.  If you prefer to keep it all rights reserved, it would still be helpful to add a license file that clarifies that.

**Comment by VirtualGaming1** [comment]
I dont know if he going to make is open source the mod but mainly the reason of have GitHub is to help find bugs and help Corosauce to fix them as well. but im not Corosauce but it up to him but this is what i am saying why it is on Gethub like my modpack for example i use it for bug reporting.

**Comment by douglasg14b** [comment]
A license file would be very nice, so those of us that might be interested in porting it to 1.16 have the ability to since the mod seems stale at this point

**Comment by douglasg14b** [comment]
I see this was closed, but I'm not finding a license? :(
