### ISSUE TITLE
Crash on pathfinding 1.12.2 latest version.

### ISSUE THREAD

**Issue by darkshadow1809** [Corosauce/ZombieAwareness#27]
Seems both errors are the same 

[crash-2017-12-28_00.47.39-server.txt](https://github.com/Corosauce/ZombieAwareness/files/1590116/crash-2017-12-28_00.47.39-server.txt)
[crash-2017-12-28_00.53.47-server.txt](https://github.com/Corosauce/ZombieAwareness/files/1590117/crash-2017-12-28_00.53.47-server.txt)

**Comment by Corosauce** [comment]
From the looks of it, I think its a bug with some block having a null bounding box, my mod just does a lot of pathfinding so it was the first to trigger the crash, not 100% sure on that but I can't see how my mod would be directly to blame. 

1. If you remove zombie awareness, I bet the crash will still happen, just might take longer to happen.
2. If you remove other mods but leave in zombie awareness, it probably wont happen.

Unfortunately there's no easy way to tell what block it was looking up when the crash happened. Will leave this issue open for now.

**Comment by darkshadow1809** [comment]
@Corosauce Hmm, Ill replace this mod with another mod that modifies the behaviour of mobs.. lets see if they cause the same error. Ill just put the mob numbers through the roof.

Funny thing is both crashes happened right after restart and keeps happening unless I put it at peaceful difficulty. which ofcourse makes sense because no more mobs so no pathfinding going on.. Now unfortunately removing mods wont tell us much as it would remove X block therefor the pathfinding cant happen. Making problem solving harder as we still dont know which block triggers it. as for which mod triggers it is even more difficult with a pack containing 170+ mods... give or take about 100~ because not all 170 mods add blocks that spawn in terrain gen. Is there a way to debug which specific block causes it? If not is there anything you can do on your side to possibly code around it? Simply giving your mobs a no go zone to null bounding blocks? I know its possible to identify which blocks are and which arent.. Maybe even let it function as a debug tool if it requires to much resources? So a mobs pathfinding would be: 

Moving to XYZ > Check for valid bounding block > If valid and not null > Move 
Moving to XYZ > Check for valid bounding block > If not valid and null > crash and report or find another path, log & report blockID?


Just throwing some idea's out there and thinking with. Cause right now I don't see a solution of fixing it easy.

**Comment by Corosauce** [comment]
I have to push a build out for another bug, so I'll just quick make my code catch the exception for now but print something small to console so you can at least keep playing.

**Comment by Corosauce** [comment]
Ok am now catching the error https://github.com/Corosauce/CoroUtil/commit/6a524c4620a6bfc912e43336e5ff573092df8421

Decided to fully output the crash, but If the log gets too spammy, set useLoggingError to false in CoroUtil.cfg

New build: CoroUtil 1.1.23: http://bit.ly/2BTHiBT

Gonna leave this open for now.

As for debugging, I'd have to modify forge to catch what specific block is causing issues for it.

You could try to keep an eye on the logs and see if it starts spitting out errors, and doing some guess work on what block it might be in your general area.

If you have some ideas as to what block from a mod it might be I could try to track it down and check things out more.

**Comment by darkshadow1809** [comment]
Awesome, thanks man! appreciate the fast work :) I'll push the update later this evening to the pack see if we can track it down once it happens again.

**Comment by darkshadow1809** [comment]
@Corosauce Is there a possibility to push this update to curse? They're not allowing me to upload the modpack with this build unfortunately ;(

**Comment by Corosauce** [comment]
Yep its there, I upload there same time, just takes time for them to approve it.

**Comment by darkshadow1809** [comment]
Thanks again ;)

**Comment by Corosauce** [comment]
Looks like its from another mod, another report unrelated to my mod I came across: https://gist.github.com/anonymous/aa82e947583cb0dabcce2b54e930012a

crash is from FTB Revelation 1.1.0

**Comment by Corosauce** [comment]
The likely culprit https://github.com/brandon3055/Draconic-Evolution/issues/1014
