### ISSUE TITLE
[1.12.2] Crash entity

### ISSUE THREAD

**Issue by GWSheridan** [Corosauce/ZombieAwareness#28]
Crash when using a portal from Nether Utils https://minecraft.curseforge.com/projects/nether-the-farm

Crash log https://pastebin.com/361vJ0Nv

latest FML https://pastebin.com/0iXdSkzs

**Comment by Corosauce** [comment]
Hoping this fixes it https://github.com/Corosauce/ZombieAwareness/commit/e4b76f32dfc06c19714097df4cb4cd36bcfc438d

new build: ZombieAwareness 1.11.11: http://bit.ly/2lnsl42

**Comment by GWSheridan** [comment]
testing now give me 10mins bud

**Comment by GWSheridan** [comment]
Fixed no crashes

**Comment by Corosauce** [comment]
Excellent!
