### ISSUE TITLE
Zombies gain super fast speed increase

### ISSUE THREAD

**Issue by Morpheus1101** [Corosauce/ZombieAwareness#3]
Im using ZA in my 1.7.10 pack and have noticed that the speed buff zombies gain makes them move so very fast its like they all have speed 100 buff its virtually impossible to hit them in combat or be able to run away.

**Comment by Corosauce** [comment]
An unfortunate conflict with old configs vs new configs and how the random speed buff is used now, pop open config/ZombieAwareness/General.cfg and set zombieRandSpeedBoost to something like 0.1 or 0.3, default is now 0.3. Set to 0 to disable.

I ran into this issue myself where the value was set to something insane like 5, sorry about that ;D

**Comment by Morpheus1101** [comment]
Ahh yes that has indeed fixed it, ive put it to 1 being max of dble normal speed and they're now moving at a reasonable speed.
