### ISSUE TITLE
[1.12.2-1.11.11] Performance impact in Losts Souls

### ISSUE THREAD

**Issue by Leosky** [Corosauce/ZombieAwareness#30]
The mod cause spike lags during combat against group of Zombie Pigmen and have a global impact on the game quite important. I noticed a 60+ fps gain when the mod have been disabled.

Here is the last logs from the modpack (four files) : https://gist.github.com/Leosky/f51fff3252acd3accc759302ecebf910

**Comment by Corosauce** [comment]
Can't reproduce with 50 pigman spawned, must be some random mod conflict of sorts. Also tweaking some things in a new build that reduces performance cost that might help.

**Comment by Corosauce** [comment]
Actually looks like 8 months ago I made sure pig zombies werent set to true for AI enhancement, that fix might have been why i couldn't reproduce it.
