### ISSUE TITLE
Server crash with both zombieawareness and farseek installed

### ISSUE THREAD

**Issue by darthvader45** [Corosauce/ZombieAwareness#33]
Had some zombies chasing me, and this crash happened.

The crash report:
https://pastebin.com/cEfvHbuC

Considering it mentioned both this mod and Farseek, I sent the crash report to its devs as well.

**Comment by Corosauce** [comment]
Its a bug in their mod, my mod is just making it more likely since it causes more pathfind calls.

**Comment by darthvader45** [comment]
Alrighty.  I sent a report to their devs, so hopefully there's a fix.
