### ISSUE TITLE
You might want to reduce the spawn rate of the scent entity

### ISSUE THREAD

**Issue by Sunconure11** [Corosauce/ZombieAwareness#35]
I decided to run my server through tickprofiler, and noticed quite an abundance of scent...

https://pastebin.com/77NLTdem

This appears to be causing a noticeable FPS drop, as well.

Run /kill @e[type=zombieawareness:EntityScent] in a world and FPS will skyrocket.

**Comment by ThunderBolt6** [comment]
on what do you have     "D:extraScentCutoffRange=" on general.cfg?

**Comment by Sunconure11** [comment]
@ThunderBolt6 1.0

**Comment by ThunderBolt6** [comment]
increase that, lower numbers = less blocks between entity scent(and i think that number is in blocks), for compison i have it on 2, and work fine even with a huge modpack(and 100 entities on the chunks loaded by player(non scent entity))

**Comment by darthvader45** [comment]
I might have to take a look.  Maybe increase the default value to around 5 or so?  Might help with lag, though it could hurt pathfinding a tad.

**Comment by ScienceDrummer** [comment]
This might be why I'm getting server lag in a single player world.

**Comment by Corosauce** [comment]
Yeah do what ThunderBolt6 suggested and that should improve it, recently noticed a high count in a private modpack, I think I might up this to at least 3 to help keep the count down.

**Comment by Corosauce** [comment]
https://github.com/Corosauce/ZombieAwareness/commit/40b4c91e19225fae6fd48863c7af9bb46deabea9
