### ISSUE TITLE
Zombies ignoring light Level

### ISSUE THREAD

**Issue by Freebi85** [Corosauce/ZombieAwareness#38]
I've noticed that random surface zombies seem to spawn in groups in lit areas. 
Not even the Mega Torch can prevent that.

**Comment by Corosauce** [comment]
The default on feature of mob duplicating on surface feature only does it where other zombies already are, and does check if its dark enough.

But if you mean the default off config of "extraSpawningSurface", then yeah I've noticed some issues with that, less so if using "extraSpawningUseNaturalSpawnList" though. The feature needs to be fleshed out more, or I should explain in the config it was more of a feature for screwing around for myself than a real feature.

**Comment by Freebi85** [comment]
Well, to be honest i don't know which config exaclty causes this. I can only say in large bases zombies will continue to spawn even if the entire area is illuminated. but it doesn't happen when you're in immediate proximity.

**Comment by Kamorzy** [comment]
Zombies constantly spawn far away during the day in my game with Features.cfg extraSpawningSurface=true.
