### ISSUE TITLE
extraSpawningUseNaturalSpawnList issue

### ISSUE THREAD

**Issue by Golrith** [Corosauce/ZombieAwareness#39]
In the spawning.cfg there is an option for extraSpawningUseNaturalSpawnList, but when even set to true only zombies spawn.

Could I suggest that this section is enhanced with an configurable array of the mob IDs that can be spawned in an horde, with a weight for each? I'd love to have some unique mobs only spawning within the hordes.

**Comment by Corosauce** [comment]
Might be worth considering, especially as I have found myself using it on servers i have OP in from time to time to give myself more challenge. The feature needs to be fleshed out more, or I should explain in the config it was more of a feature for screwing around for myself than a real feature.

**Comment by Golrith** [comment]
Thanks for considering. ZA is a great mod that I always use. Makes zombies more of a challenge.
