### ISSUE TITLE
Server crash 1.10 on 1.7.10

### ISSUE THREAD

**Issue by tgstyle** [Corosauce/ZombieAwareness#4]
This crash happens on a server when a client connects.

https://gist.github.com/tgstyle/c36311ea36db1eb6805f0ff4efe2c3b8

**Comment by Zottel** [comment]
Same thing happening on 1.10.2?
https://gist.github.com/Zottel/6622869ba4ddfd059450f3a70e2f7460

**Comment by LakMoore** [comment]
CoroSauce has not commented on the patch but I am using it in a production environment and it works.  You should be able to copy the same code into the 1.10.2 version and compile it for yourself, unless CoroSauce decides to apply this patch.

**Comment by Corosauce** [comment]
A dumb bug on my part now fixed for mc 1.10.2, not sure if will fix in 1.7.10, you can just disable speed boosted mobs in config, see https://github.com/Corosauce/ZombieAwareness/issues/12 for more info on how to do that
