### ISSUE TITLE
zombie awareness mod

### ISSUE THREAD

**Issue by Darkphoenix050** [Corosauce/ZombieAwareness#43]
the config option does not work I cannot click it pls  help or fix it

**Comment by lolsteamroller** [comment]
Use \config\ZombieAwareness - all the files are there to modify to your needs.

**Comment by mailleseraph** [comment]
pretty sure this mod isn't being updated for 1.12 anymore but I will leave this here: it seems the configs don't work on a server, on a single player world they work fine, but nothing changes if you play it on a multiplayer server.
