### ISSUE TITLE
Sound physics compatibility issue

### ISSUE THREAD

**Issue by jackg2527** [Corosauce/ZombieAwareness#58]
Hello, Very happy to see your mod updated! Unfortunately, some sounds get muted if 1.18.1 version is installed along with Sound Physics (https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered). 

I just posted issue on Sound Physics page https://github.com/henkelmax/sound-physics-remastered/issues/22#issue-1091969170, pasted below as well. Thanks in advance for your help. Jack

Bug description

Hi there, when I use this mod with Zombie Awareness, some sounds are muted: zombie growling and other mob sounds, mobs reaction to damage, no sound when firing bow. Other sounds such as hitting/breaking blocks are not affected. Looks like same issue posted yesterday #21 (comment)

If I remove Sound Physics OR Zombie Awareness, all sounds are back to normal. Will also post this on ZA site.

Anything you guys could do would be greatly appreciated. Two of my favorite mods and trying to choose between them is just...killing...me.

Many thanks!
Jack

Versions
zombieawareness-1.18.1-1.12
coroutil-1.18.1-1.2.37
soundphysics-forge-1.18.1-1.0.3
Forge: 39.0.9

Steps to reproduce the issue
See above.

Expected behavior
Normal sounds!

Log files
I'm attaching latest.log and debug.log files since I dunno what will help you. Four files:

ZAonly_: latest and debug with just ZA and CoroUtil installed, all sounds working
ZAandSoundPhys_: same files after adding Sound physics, sound issue occurs

[ZAonly_latest.log](https://github.com/Corosauce/ZombieAwareness/files/7798768/ZAonly_latest.log)
[ZAonly_debug.log](https://github.com/Corosauce/ZombieAwareness/files/7798769/ZAonly_debug.log)
[ZAandSoundPhys_latest.log](https://github.com/Corosauce/ZombieAwareness/files/7798770/ZAandSoundPhys_latest.log)
[ZAandSoundPhys_debug.log](https://github.com/Corosauce/ZombieAwareness/files/7798771/ZAandSoundPhys_debug.log)

**Comment by Corosauce** [comment]
Fixed https://github.com/Corosauce/ZombieAwareness/commit/db926bdbd7b2ce87ce9d1d485feb58cdedf84a1d

Release: https://www.curseforge.com/minecraft/mc-mods/zombie-awareness/files/3603741

**Comment by jackg2527** [comment]
All good. Thanks again. You da man.

**Comment by antoniovcampbell** [comment]
can you pls update to 1.18.2?
