### ISSUE TITLE
[1.18.1] ZA causing long tick and crashing

### ISSUE THREAD

**Issue by itsdinkd** [Corosauce/ZombieAwareness#59]
I've been getting this crash randomly since adding the mod, probably around every 2-3 hours. Most recently and how I discovered I 've been getting this crash (didn't check crash logs until now and saw a bunch of reports with this same crash) I teleported myself to 14500 60 14500 and then the server crashed.

Crash from teleport (most recent); https://pastebin.com/JZ3dSkZ9
Second recent crash; https://pastebin.com/rawph41d

**Comment by itsdinkd** [comment]
THis doesnt occur anymore with the mod removed.

**Comment by Corosauce** [comment]
Haven't been able to reproduce, but I made some optimizations that likely fix this issue, seems Minecrafts newer chunk generation can be a bit more prone to getting backlogged, give this update a try: https://www.curseforge.com/minecraft/mc-mods/zombie-awareness/files/3600617

If there's still issues you can disable the problem code by setting awareness_Sound to False in config/zombieawareness/Features.toml

**Comment by lamoyrl90** [comment]
Still getting this issue with awareness_Sound set to true in version 1.18.1-1.12.1, although it doesn't seem quite as bad. Before, when I'd teleport to large structures I'd freeze before the teleport happened clientside, but now the game at least allows me to teleport before it freezes. The "freeze" is just a long tick, where I can still move around but nothing in the world updates.

Setting awareness_Sound to false still solves the issue. Maybe there's a different way to check if the game should spawn a sound source.

**Comment by lgnmcrules** [comment]
Hello, I've been experiencing this same issue in your 1.16.5 version of this mod.  Could you also implement the fix on that version?
