### ISSUE TITLE
【BUG】Entering the end city, the game crashes ！！！

### ISSUE THREAD

**Issue by blood789** [Corosauce/ZombieAwareness#61]
I enter The End，  use /locate endcity ,to find endcity....

when  I  entering the end city, the game crashes ！！！

Version : 1.18.1

Forge : 1.18.1-39.0.10

After, I disable the mod (ZombieAwareness) , and create a new game , enter a endcity again, it run well , and do not crashes again. 

Can you fix this bug, I want to add to my modpack , Thanks !

[latest.log](https://github.com/Corosauce/ZombieAwareness/files/7832580/latest.log)
[debug.log](https://github.com/Corosauce/ZombieAwareness/files/7832601/debug.log)
[latest-01-08.log](https://github.com/Corosauce/ZombieAwareness/files/7832602/latest-01-08.log)

**Comment by blood789** [comment]
AT that time, all the enderman are still, no longer to move.
I can not use any command in the endcity, it is no response.
And I  can not save and leave the game. The whole program is stuck.

I can only turn off the game through the task manager in windows 11 system......

**Comment by Corosauce** [comment]
I think its the same as https://github.com/Corosauce/ZombieAwareness/issues/59

I've linked a new build that should fix this there.
