### ISSUE TITLE
Server freezes when generating new chunks in 1.16.5

### ISSUE THREAD

**Issue by Longer-than-average-username** [Corosauce/ZombieAwareness#64]
You appear to have fixed this in 1.18.1 but i just wanted to tell you that it can also happen in the 1.16.5 version aswell!
The game freezes shortly after generating new chunks in an old world after installing the mod or shortly after generating a new world.
I got a massive modpack so im not surprised when some things break every now and then but its a shame i cant use this cool mod right now.

[crash-2022-01-17_00.14.22-server.txt](https://github.com/Corosauce/ZombieAwareness/files/7878222/crash-2022-01-17_00.14.22-server.txt)

**Comment by Longer-than-average-username** [comment]
Forgot to mention it still happens even if i turn off sound and scent sources in the config, that report is the most recent so it will be the one with those features turned off

**Comment by FernoXL** [comment]
I am Also Experiencing this Issue. Whenever I travel close to a large generated structure or far enough away from spawn the game will freeze and will need to be force closed/crashed. Sadly I am not getting a crash report when this happens.

**Comment by Nostdorm** [comment]
Same here for me on 1.16.5
Once I go to a certain place - server freezes, players are kicked due to a timeout.
Disabling ZA obviously fixes that
[crash-2022-03-11_00.26.12-server.txt](https://github.com/Corosauce/ZombieAwareness/files/8227644/crash-2022-03-11_00.26.12-server.txt)
.

**Comment by Figgmastah** [comment]
Me to, For me it happens when loading a structure from Mowzie's Mobs
