### ISSUE TITLE
[1.10.2] Server crash on world start

### ISSUE THREAD

**Issue by The-Fireplace** [Corosauce/ZombieAwareness#7]
http://paste.ubuntu.com/23365086/
Zombie Awareness 1.20

**Comment by Lanaess** [comment]
I have the exact same error as @The-Fireplace above. Server Crashes when a client connects. Also my processor runs at 100% with no users. 

My mod list is different from above:
CustomNPC, tnt_utilities, worldedit, coroutil-1.10.2-1.1.9, and zombieawareness-1.10.2-1.20.

**Comment by Corosauce** [comment]
Duplicate of https://github.com/Corosauce/ZombieAwareness/issues/10 and should be fixed now since release of 1.11.1 (weird version change but its newer than 1.20)
