### ISSUE TITLE
zombie awarness has failed to load correctly, even independently

### ISSUE THREAD

**Issue by iwillbeurdad** [Corosauce/ZombieAwareness#70]
so ive been downloading a few mods, uploaded them all properly with their supporting mods, and all of them function perfectly. but when it comes down to this mod it constantly says it fails to load correctly every single time including when it is independent and free of any other mod. is it a common issue going into 1.18? and yes ive downloaded the correct version.

message that pops up is as follows below the failed to load correctly prompt: 
java.lang.NoClassDefFoundError: com/corosus/modconfig/IconfigCatagory

**Comment by Corosauce** [comment]
needed coroutil, i used to have a cleaner message that pops up about this but it was lost in the sea of updates.
