### ISSUE TITLE
Zombie Awareness has failed to load correctly

### ISSUE THREAD

**Issue by AlriiK** [Corosauce/ZombieAwareness#73]
The error occurred when loading all the mods, forge has shown me this:
java.lang.NoClassDefFoundError: com/corosus/modconfig/IConfigCategory
![image](https://user-images.githubusercontent.com/63112421/155765687-400a3f64-4c59-4618-9662-6dd1ba8786c9.png)

I have made a personal modpack for me and my friends, with like 140+ mods inside it.

**Comment by FelixFF12** [comment]
what shud i do now ?

**Comment by nightlord33** [comment]
you have instaled CoroUtil ?
my game was crashing too but after instaling that it run smooth
