### ISSUE TITLE
crashing in the End

### ISSUE THREAD

**Issue by Lightaseption** [Corosauce/ZombieAwareness#78]
well somewhere in the End when we go in server will crash and i asked a Nerd guy he said cuz of Zombie Awareness is accessing the world when it is unavailable
here is a Crash report
[crash-2022-04-11_03.30.25-server.txt](https://github.com/Corosauce/ZombieAwareness/files/8461027/crash-2022-04-11_03.30.25-server.txt)

**Comment by dhyces** [comment]
from ServerChunkCache#getChunk javadoc:
`/**
    * Gets the chunk at the provided position, if it exists.
    * Note: This method <strong>can deadlock</strong> when called from within an existing chunk load, as it will be
    * stuck waiting for the current chunk to load!
    * @param pLoad If this should force a chunk load. When {@code false}, this will return null if the chunk is not
    * loaded.
    */`
The call in ZAUtil#canSpawnTrace to get the blockstate seems to cause this to happen.

**Comment by JdaxCZ** [comment]
I believe I ran into the same issue, after some testing, it appears that the game crashes when attempting to load an end city with an elytra, specifically whenever the chunk that contains the ship attempts to load - in singleplayer, the game's internal server completely freezes, you can move around, but you cannot drop items, hit entities, and no modifications are saved, you cannot quit the game as it gets stuck at saving the world. On a server, the server crashes with an error message that one tick took 60 seconds
