### ISSUE TITLE
Server not starting (1.16.5)

### ISSUE THREAD

**Issue by IRetr0** [Corosauce/ZombieAwareness#80]
Everytime the Server tries to start with this mod installed I get console spam of the following:

`[Netty Epoll Server IO #13/INFO] [ne.mi.fm.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting. `

I can't solve this problem on my own...

**Comment by Thelegendking** [comment]
I'm having the same kind of problem my loading screen is stuck 100% when I open an existing world with it in 1.16.5 but it gets fixed when I remove this mod.
