### ISSUE TITLE
Integrated Server Freeze 

### ISSUE THREAD

**Issue by Aninz** [Corosauce/ZombieAwareness#83]
I played this mod in 1.16.5 forge SinglePlayer, the problem was the Integrated Server Freeze if im using Zombie Awareness 1.16 I don't know what the caused of it. Is there a fix that doesn't need to update the mod , I really love this mod due its difficulty

**Comment by deadspidervenom** [comment]
It seems the mod causes some severe lag, as i was having this issue, but as i removed mods bug fixing things got less unstable, till i removed zombie awareness and it clear up completely.

I used "VisualVM" and check server threads in the thread dump file.
