### ISSUE TITLE
Existing world loading stuck at 100% in 1.16.5

### ISSUE THREAD

**Issue by Thelegendking** [Corosauce/ZombieAwareness#87]
Existing world loading gets stuck at 100% at singleplayer world when installing this mod but it gets fixed when removing this mod. And yes I did install its dependency mod coroutill I think its name is? So yeah the world is not loading.

**Comment by UselessBullets** [comment]
It sounds similar to my issue, https://github.com/Corosauce/ZombieAwareness/issues/98
You could try using a tool like MCA Selector to edit chunk data to remove the item frame entity and see if that fixes it.

**Comment by Corosauce** [comment]
Until I backport a proper fix I'll recommend that freeze-fix mod for now https://github.com/Corosauce/ZombieAwareness/issues/98#issuecomment-1445403198
