### ISSUE TITLE
ZombieAwareness failing to load mc1.19.2 forge 43.1.30

### ISSUE THREAD

**Issue by litjohn50** [Corosauce/ZombieAwareness#89]
Mc 1.19.2 
Forge 43.1.30
[latest.log](https://github.com/Corosauce/ZombieAwareness/files/9680201/latest.log)

Fails to load in forge version 43.1.30, but loads in forge 43.1.29

**Comment by GWSheridan** [comment]
Think im having the same issue on load up

https://pastebin.com/wBX5exCe

**Comment by ProsperCraft** [comment]
https://gist.githubusercontent.com/ProsperCraft/3ae458eb68937685ef9451624dd44597/raw/eb2a81650209ae19d966bb10ff89356a36c34b1c/gistfile1.txt

Same with forge-1.19.2-43.1.32

**Comment by LordDecay26** [comment]
i am experiencing the same issue
https://pastebin.com/XgqhYSy9

(finally, a normal bug that i can report like a normal person and that other people are experiencing, this is rare for me)

**Comment by LibertyDev-1** [comment]
The same bug pops up when I boot up the game. forge-1.19.2-43.1.30.

**Comment by LordDecay26** [comment]
i just hope this gets fixed before Halloween, i really need this in my horror modpack.

**Comment by LordDecay26** [comment]
welp, too late, oh well
hope everyone had an adequately haunted harvest

**Comment by brentopc** [comment]
Having this issue as well

**Comment by SeldomSpirit** [comment]
So... no one can get this going eh?

**Comment by brentopc** [comment]
There is a hidden version that works
________________________________

**Comment by FaithDisc0rd** [comment]
same issue...

**Comment by Corosauce** [comment]
Guess they finally enforced that at some point, my multiloader version of coroutil backported that fix anyways so it should be fine now.
