### ISSUE TITLE
The mod don't run

### ISSUE THREAD

**Issue by Symbiosine** [Corosauce/ZombieAwareness#90]
Hello,
when i launch the mod in 1.19.2 (zombieawareness-1.19.2-1.12.3.jar)
that show me this message : java.lang.reflect.InvocationTargetException: null

I have only Zombieawarness and coroutil-1.19.2-1.2.37 in my mods file.

**Comment by LordDecay26** [comment]
i suggest merging this issue with this thread
same issue as #89

**Comment by Corosauce** [comment]
Guess they finally enforced that at some point, my multiloader version of coroutil backported that fix anyways so it should be fine now.
