### ISSUE TITLE
Request to port to fabric 1.19.2

### ISSUE THREAD

**Issue by ClaraOswald666** [Corosauce/ZombieAwareness#91]
As the title suggests is there any possibility it will be ported to fabric?

**Comment by DaCooladeMan** [comment]
Man, no response. Sad... I also want it ported to fabric 1.20+

I'm not particularly looking for the enhanced zombie AI, however. I want the little bleeding effect as a little small detail for when you take damage, and have been looking for mods that do this. This mod is what I was looking for, but... it's for Forge and has not been updated to 1.20... sad.
